# Generated by Django 5.2.4 on 2025-11-11 14:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hid from menu')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in dollars like 4.50', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_available', models.BooleanField(default=True)),
                ('stock_count', models.PositiveIntegerField(default=0, help_text='For beanss/merch')),
                ('low_stock_threashold', models.PositiveIntegerField(default=5)),
                ('is_coffee_drink', models.BooleanField(default=False)),
                ('caffeine_mg', models.PositiveIntegerField(blank=True, null=True)),
                ('is_merch', models.BooleanField(default=False)),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('featured', models.BooleanField(default=False)),
                ('prep_time_minutes', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='set to null if category is deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-featured', 'name'],
                'indexes': [models.Index(fields=['category', 'is_available'], name='products_pr_categor_c898cc_idx'), models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'), models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx')],
            },
        ),
    ]
